name: Simple NodeJS Docker Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 02_expressWeb

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Verify Node version
      run: node -v

    - name: Say hi
      run: echo "✅ GitHub Actions is working for 02_expressWeb!"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: abhishekkumar1402
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Debug docker info
      run: docker info

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./02_expressWeb
        file: ./02_expressWeb/Dockerfile
        push: true
        tags: abhishekkumar1402/expressweb:new

    - name: Show image pushed
      run: echo "✅ Image pushed:abhishekkumar1402/expressweb:new"

